### ISSUE TITLE
OpenMP Target reduction with result in host rank 1 view fails to compile

### ISSUE THREAD

**Issue by lucbv** [kokkos/kokkos#4410]
Hi all, I am seeing the following error when compiling Kokkos Kernels against Kokkos with OpenMP Target enabled:
```
In file included from /gpfs/alpine/scratch/lberge/csc465/builds/ompt_cuda/kk_lucbv/src/impl/generated_specializations_cpp/sum/Blas1_sum_mv_eti_DOUBLE_LAYOUTLEFT_EXECSPACE_OPENMPTARGET_MEMSPACE_OPENMPTARGETSPACE.cpp:48:
In file included from /ccs/proj/csc465/lberge/kokkoskernels_root/sources/kk_lucbv/src/blas/impl/KokkosBlas1_sum_spec.hpp:48:
In file included from /gpfs/alpine/scratch/lberge/csc465/installs/ompt_cuda/kokkos/include/Kokkos_Core.hpp:56:
In file included from /gpfs/alpine/scratch/lberge/csc465/installs/ompt_cuda/kokkos/include/KokkosCore_Config_DeclareBackend.hpp:47:
In file included from /gpfs/alpine/scratch/lberge/csc465/installs/ompt_cuda/kokkos/include/decl/Kokkos_Declare_OPENMPTARGET.hpp:49:
In file included from /gpfs/alpine/scratch/lberge/csc465/installs/ompt_cuda/kokkos/include/Kokkos_OpenMPTarget.hpp:157:
/gpfs/alpine/scratch/lberge/csc465/installs/ompt_cuda/kokkos/include/OpenMPTarget/Kokkos_OpenMPTarget_Parallel.hpp:245:72: error: subscripted value is not an array or pointer
#pragma omp target teams distribute parallel for map(to:f) reduction(+:result[:NumReductions])
                                                                       ^~~~~~
/gpfs/alpine/scratch/lberge/csc465/installs/ompt_cuda/kokkos/include/OpenMPTarget/Kokkos_OpenMPTarget_Parallel.hpp:451:39: note: in instantiation of function template specialization 'Kokkos::Impl::ParallelReduceSpecialize<KokkosBlas::Impl::MV_Sum_Right_FunctorVector<Kokkos::View<double *, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<1>>, Kokkos::View<const double **, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Experimental::OpenMPTarget, Kokkos::Experimental::OpenMPTargetSpace>, Kokkos::MemoryTraits<1>>, int>, Kokkos::RangePolicy<Kokkos::Experimental::OpenMPTarget, int>, Kokkos::InvalidType, double *, double>::execute_array<void, 2>' requested here
        ParReduceSpecialize::template execute_array<TagType, 2>(
                                      ^
/gpfs/alpine/scratch/lberge/csc465/installs/ompt_cuda/kokkos/include/Kokkos_Parallel_Reduce.hpp:877:13: note: in instantiation of member function 'Kokkos::Impl::ParallelReduce<KokkosBlas::Impl::MV_Sum_Right_FunctorVector<Kokkos::View<double *, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<1>>, Kokkos::View<const double **, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Experimental::OpenMPTarget, Kokkos::Experimental::OpenMPTargetSpace>, Kokkos::MemoryTraits<1>>, int>, Kokkos::RangePolicy<Kokkos::Experimental::OpenMPTarget, int>, Kokkos::InvalidType, Kokkos::Experimental::OpenMPTarget>::execute' requested here
    closure.execute();
            ^
/gpfs/alpine/scratch/lberge/csc465/installs/ompt_cuda/kokkos/include/Kokkos_Parallel_Reduce.hpp:1068:69: note: in instantiation of member function 'Kokkos::Impl::ParallelReduceAdaptor<Kokkos::RangePolicy<Kokkos::Experimental::OpenMPTarget, int>, KokkosBlas::Impl::MV_Sum_Right_FunctorVector<Kokkos::View<double *, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<1>>, Kokkos::View<const double **, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Experimental::OpenMPTarget, Kokkos::Experimental::OpenMPTargetSpace>, Kokkos::MemoryTraits<1>>, int>, Kokkos::View<double *, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<1>>>::execute' requested here
  Impl::ParallelReduceAdaptor<PolicyType, FunctorType, ReturnType>::execute(
                                                                    ^
/ccs/proj/csc465/lberge/kokkoskernels_root/sources/kk_lucbv/src/blas/impl/KokkosBlas1_sum_impl.hpp:225:13: note: in instantiation of function template specialization 'Kokkos::parallel_reduce<Kokkos::RangePolicy<Kokkos::Experimental::OpenMPTarget, int>, KokkosBlas::Impl::MV_Sum_Right_FunctorVector<Kokkos::View<double *, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<1>>, Kokkos::View<const double **, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Experimental::OpenMPTarget, Kokkos::Experimental::OpenMPTargetSpace>, Kokkos::MemoryTraits<1>>, int>, Kokkos::View<double *, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<1>>>' requested here
    Kokkos::parallel_reduce("KokkosBlas::Sum::S1", policy, op, r);
            ^
/ccs/proj/csc465/lberge/kokkoskernels_root/sources/kk_lucbv/src/blas/impl/KokkosBlas1_sum_spec.hpp:202:7: note: in instantiation of function template specialization 'KokkosBlas::Impl::MV_Sum_Invoke<Kokkos::View<double *, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<1>>, Kokkos::View<const double **, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Experimental::OpenMPTarget, Kokkos::Experimental::OpenMPTargetSpace>, Kokkos::MemoryTraits<1>>, int>' requested here
      MV_Sum_Invoke<RV, XMV, int>(R, X);
```

The issues is related to how the parallel reduction is implemented in the OpenMP Target backend (see `core/src/OpenMPTarget/Kokkos_OpenMPTarget_Parallel.hpp`), a possible fix is proposed below:
```c++
template <class TagType, int NumReductions>
  static void execute_array(const FunctorType& f, const PolicyType& p,
                            PointerType result_ptr, bool ptr_on_device) {
    OpenMPTargetExec::verify_is_process(
        "Kokkos::Experimental::OpenMPTarget parallel_for");
    OpenMPTargetExec::verify_initialized(
        "Kokkos::Experimental::OpenMPTarget parallel_for");
    const auto begin = p.begin();
    const auto end   = p.end();

    if (end <= begin) return;

    // Enter the loop if the reduction is on a scalar type.
    if constexpr (NumReductions == 1) {

      ValueType result = ValueType();

      // Case where reduction is on a native data type.
      if constexpr (std::is_arithmetic<ValueType>::value) {
#pragma omp target teams distribute parallel for \
         map(to:f) reduction(+: result)
        for (auto i = begin; i < end; ++i)

          if constexpr (std::is_same<TagType, void>::value) {
            f(i, result);
          } else {
            f(TagType(), i, result);
          }

        ParReduceCommon::memcpy_result(result_ptr, &result, sizeof(ValueType),
                                   ptr_on_device);
      } else {
#pragma omp declare reduction(custom:ValueType : omp_out += omp_in)
#pragma omp target teams distribute parallel for map(to                    \
                                                     : f) reduction(custom \
                                                                    : result)
        for (auto i = begin; i < end; ++i)

          if constexpr (std::is_same<TagType, void>::value) {
            f(i, result);
          } else {
            f(TagType(), i, result);
          }
      }
        ParReduceCommon::memcpy_result(result_ptr, &result, sizeof(ValueType),
                                   ptr_on_device);
    } else {

        ValueType result[NumReductions] = {};

#pragma omp target teams distribute parallel for map(to:f) reduction(+:result[:NumReductions])
      for (auto i = begin; i < end; ++i) {
        if constexpr (std::is_same<TagType, void>::value) {
          f(i, result);
        } else {
          f(TagType(), i, result);
        }
      }

        ParReduceCommon::memcpy_result(result_ptr, result, sizeof(ValueType),
                                   ptr_on_device);
    }

  }
```

**Comment by lucbv** [comment]
Sure, I'll look into a reproducer.
There is an additional issue that is not addressed by the fix above related to the update of the results which require the size of the array in addition to the pointer.

**Comment by psteinbrecher** [comment]
The whole API has to be changed as well. You need to pass down the user ptr size (m_result_ptr_num_elems) so that you can use it for the memcpy.

Just using:
ParReduceCommon::memcpy_result(result_ptr, result, NumReductions*sizeof(ValueType), ptr_on_device);

is wrong. You have to use:
ParReduceCommon::memcpy_result(result_ptr, result, m_result_ptr_num_elems*sizeof(ValueType), ptr_on_device);

but m_result_ptr_num_elems is not part of execute_array fuction parameter. So it has to be added.

**Comment by ajpowelsnl** [comment]
Hi @lucbv and @rgayatri23 -- is this issue still active?

**Comment by ajpowelsnl** [comment]
Hi @lucbv and @rgayatri23 -- are we still having this compilation failure with OpenMPTarget reductions?  Please let me know so that I can update or close this issue in the next few days.

**Comment by cwpearson** [comment]
OpenMPTarget removed in #8717
